---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/mnenad/PCF-demo.git
      branch: master

  - name: cf-dev
    type: cf
    source:
      api: api.run.pivotal.io
      username: momcilovicnenad@yahoo.com
      password: pivotal
      organization: Nenad
      space: dev-man
      skip_cert_check: true
  
  - name: cf-test
    type: cf
    source:
      api: api.run.pivotal.io
      username: momcilovicnenad@yahoo.com
      password: pivotal
      organization: Nenad
      space: test-man
      skip_cert_check: true


jobs:
  - name: build
    public: true
    plan:
      - get: source-code
        trigger: true
      - task: build
        file: source-code/ci/tasks/build.yml
      - put: cf-dev
        params:
          manifest: source-code/manifest.yml
          path: build-output/pcfdemo.war
          
  - name: deploy test
    public: true
    plan:
      - get: source-code
        passed: ["build"]
      - task: build
        file: source-code/ci/tasks/build.yml
      - put: cf-test
        params:
          manifest: source-code/manifest.yml
          path: build-output/pcfdemo.war

          
          